FMB Transp CRUD/WebApp/Models/ComponentesForm/ItemDropDown.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Amon.Web.Models.ComponentesForm
{
    public class ItemDropDown
    {
        public String Name { get; set; }
        public String Value { get; set; }

        public ItemDropDown(String name, String value)
        {
            this.Name = name;
            this.Value = value;
        }
    }
}

FMB Transp CRUD/WebApp/Models/ErroModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Amon.PontoE.WebApp.Models
{
    public class ErroModel
    {
        public String Titulo { get; set; }
        public String Mensagem { get; set; }

        public ErroModel(String titulo, String mensagem)
        {
            this.Titulo = titulo;
            this.Mensagem = mensagem;
        }
    }
}

FMB Transp CRUD/WebApp/Models/Formularios/ModelFiltroPlanoDeContas.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Amon.Web.Models.Formularios
{
    public class ModelFiltroPlanoDeContas
    {
        //CAMPOS DO FILTRO.
    }
}

FMB Transp CRUD/WebApp/Models/Listagens/ModelListaPlanoDeConta.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Amon.Web.Models.Listagens
{
    public class ModelListaPlanoDeConta
    {
        //CAMPOS A SEREM EXIBIDOS NA TABELA
    }
}

FMB Transp CRUD/WebApp/Models/ModelConsultaPlanoDeContas.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using Amon.Web.Models.Formularios;
using Amon.Web.Models.Listagens;
using Amon.Modelo.Entidades;

namespace Amon.Web.Models
{
    public class ModelConsultaPlanoDeContas
    {
        public ModelFiltroPlanoDeContas filtro { get; set; }
        public IList<ModelListaPlanoDeConta> lista { get; set; }

        public ModelConsultaPlanoDeContas()
        {
            this.filtro = new ModelFiltroPlanoDeContas();
            this.lista = new List<ModelListaPlanoDeConta>();
        }
    }
}

FMB Transp CRUD/WebApp/Models/ModelTelaListagem.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using Amon.Modelo.Entidades;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace Amon.Web.Models
{
    public class ModelTelaListagem
    {
        public PlanoDeContas obj { get; set; }
        public IList<PlanoDeContas> lista { get; set; }

        public ModelTelaListagem()
        {
            this.obj = new PlanoDeContas();
            this.lista = new List<PlanoDeContas>();
        }
    }
}

FMB Transp CRUD/WebApp/Controllers/PlanoDeContasController.cs
using Amon.Modelo.Entidades;
using Amon.Web.Models;
using Amon.Web.Models.ComponentesForm;
using Amon.Servico.PlanoContas;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Amon.Web.Utils;
using Amon.Nucleo.Utils;

namespace Amon.Web.Controllers
{
    public class PlanoDeContasController : Controller
    {
        private const String actionConsulta = "Index",
                             actionCadastro = "Cadastro";
        private PlanoDeContasServico servico = new PlanoDeContasServico();

        // GET: PlanoDeContas
        public ActionResult Index(int? status = null)
        {
            PlanoDeContas objPesquisado = new PlanoDeContas();
            ModelTelaListagem modelo = new ModelTelaListagem();
            if (TempData.ContainsKey("Filtro"))
            {
                if(TempData["Filtro"].GetType().IsEquivalentTo(typeof(PlanoDeContas))) { 
                    modelo.lista = servico.ObterPorFiltro(TempData["Filtro"] as PlanoDeContas);
                    TempData.Remove("filtro");
                    if (!modelo.lista.Any())
                        status = Mensagens.NotificacaoNenhumItemEncontrado;
                }
                else if (TempData["Filtro"] == "TODOS")
                    modelo.lista = servico.obterTodos();
                else
                    status = Mensagens.NotificacaoErro;
            }

            #region  Construção do combobox
            //Estes itens podem vir de um enumerador ou da base
            List <ItemDropDown> itens = new List<ItemDropDown>();
            itens.Add(new ItemDropDown("Item 1", "1"));
            itens.Add(new ItemDropDown("Item 2", "2"));
            itens.Add(new ItemDropDown("Item 3", "3"));
            ViewBag.ItensDropDown = itens;
            #endregion

            if (status != null)
                ViewBag.InfoMsg = Mensagens.GetStatusMessage(status);

            return View(modelo);
        }

        //Ações do formulário:
        //Pesquisa
        [HttpPost]
        public ActionResult ResultadoPesquisa(ModelTelaListagem modelo)
        {
            TempData["Filtro"] = modelo.obj;
            return RedirectToAction(actionConsulta);
        }

        [HttpPost]
        public ActionResult ObterTodos()
        {
            TempData["Filtro"] = "TODOS";
            return RedirectToAction(actionConsulta);
        }

        [HttpPost]
        public ActionResult AcaoSecundaria(ModelTelaListagem modelo)
        {
            return RedirectToAction(actionConsulta);
        }

        public ActionResult LinkSimples()
        {
            return RedirectToAction(actionConsulta);
        }


        //Ações dos itens de lista:
        [HttpPost]
        public ActionResult Excluir(String cli, String con)
        {
            int feedback = Mensagens.NotificacaoErro;

            try { 
                PlanoDeContas pc = servico.obterPorChaves(cli, con);
                servico.excluir(pc);
                feedback = Mensagens.NotificacaoSucesso;
            }
            catch (Exception)
            {
                //Não é necessário implementar
            }

            return RedirectToAction(actionConsulta, new { status = feedback });
        }

        #region PENDENTE
        [HttpPost]
        public JsonResult CarregaDadosEdicao(String cli, String con)
        {
            PlanoDeContas plano = new PlanoDeContasServico().obterPorChaves(cli, con);
            return Json(new { planoEmEdicao = plano }, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public ActionResult AtualizarPlanoDeContas(PlanoDeContas dependente)
        {
            //try
            //{
            //    new DependenteServico().atualizar(dependente);
            //}
            //catch (Exception e)
            //{
            //    TempData["ErroMsg"] = Mensagens.ErroCadastroDependente;
            //}

            return RedirectToAction(actionConsulta);
        }
        #endregion

        //Abre o formulário de cadastro
        public ActionResult Cadastro()
        {
            PlanoDeContas plano = new PlanoDeContas();
            return View(plano);
        }
        
        //Faz a persistência na base
        [HttpPost]
        public ActionResult Cadastrar(PlanoDeContas plano)
        {
            int feedback = Mensagens.NotificacaoErro;
            
            if (servico.obterPorChaves(plano.CodCli.Value, plano.CodContas.Value) != null)
            {
                //Verificar primeiramente a existência do cliente e da conta
            }
            else if (false) 
            {
                //esse IF deve verificar a tabela de clientes e identificar se o código inserido existe. O mesmo deve ser feito com o código da conta.
            }
            else {
                plano.DataCriacao = DateTime.Now;

                try
                {
                    servico.incluir(plano);
                    feedback = Mensagens.NotificacaoSucesso;
                    TempData["Filtro"] = plano;
                }
                catch(Exception e) {
                    //Não é necessário implementar
                }
            }

            return RedirectToAction(actionConsulta, new { status = feedback });
        }
    }
}

FMB Transp CRUD/WebApp/Views/Funcionario/Index.cshtml
@using Amon.PontoE.WebApp.Helpers
@using PagedList;

@model IPagedList<Amon.PontoE.Modelo.Cadastro.Funcionario>

@{
    ViewBag.Title = "Funcionario";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<section id="widget-grid">
    @using (Html.iniciarLayout().setarTitulo(ViewBag.Title).setarIcone("fa fa-list").desenhar("lista"))
    {
        <div id="linhas" class="table-responsive">
            @Html.Partial("_ListaGrid", Model)
        </div>
    }
    @section paginacao{
        <div id="oncomplete"></div>
    }
</section>

FMB Transp CRUD/WebApp/Views/Funcionario/_ListaGrid.cshtml
@using PagedList;
@using Amon.PontoE.Modelo.Cadastro
@model IPagedList<Funcionario>
<div class="padding-10 dt-wrapper" role="grid">
    <table class="table table-striped table-bordered table-hover dataTable">
        <thead>
            <tr>
                <th>Id</th>
                <th>Nome</th>
                <th>Cpf</th>
                <th>Pis</th>
                <th>MatriculaRH</th>
                <th>LoginAD</th>
                <th>IdCargo</th>
                <th>IdLotacao</th>
                <th>Admissao</th>
                <th>Nascimento</th>
                <th>IdJornada</th>
                <th class="actCol">Ações</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var e in Model)
            {
                <tr>
                    <td>@e.Id</td>
                    <td>@e.Nome</td>
                    <td>@e.Cpf</td>
                    <td>@e.Pis</td>
                    <td>@e.MatriculaRH</td>
                    <td>@e.LoginAD</td>
                    <td>@e.IdCargo</td>
                    <td>@e.IdLotacao</td>
                    <th>@e.Admissao</th>
                    <td>@e.Nascimento</td>
                    <td>@e.IdJornada</td>
                    <td class="actCol">
                        <a class="text-success" href="@Url.Action("Manutencao")/@e.Id" title="Editar" rel="tooltip" data-placement="top" data-original-title="Editar"><i class="fa fa-pencil fa-lg"></i></a>&nbsp;&nbsp;
                        <a class="text-danger btn-apagar" href="@Url.Action("Excluir")/@e.Id/@Url.RequestContext.HttpContext.Request["pagina"]" title="Excluir" rel="tooltip" data-placement="top" data-original-title="Excluir"><i class="fa fa-trash-o fa-lg"></i></a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>
@Html.Partial("_Paginador", Model)

FMB Transp CRUD/WebApp/Views/MasterPages/_LayoutPadrao.cshtml
<!DOCTYPE html>
<html lang="pt-Br">
<head>
    <meta charset="utf-8" />
    <meta http-equiv="x-ua-compatible" content="IE=9" />
    <meta name="description" content="overview &amp; stats" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
    <meta name="copyright" content="Desenvolvido por AMON Consultoria em T.I." />

    <!-- IMPORTAÇÃO DE RECURSOS -->
    <!-- jquery -->
    <script src="~/Scripts/Material/jquery-3.1.0.min.js"></script>
    <script src="~/Scripts/Material/jquery-ui.min.js"></script>
    <!-- material design lite -->
    <script defer src="~/Scripts/Material/material.js"></script>
    <link rel="stylesheet" href="~/Scripts/Material/material.css" />
    <link rel="stylesheet" href="~/Scripts/Material/material.green-white.min.css" />
    <link rel="stylesheet" href="~/Scripts/Material/material-icons.css" />
    <!-- extensão material design lite -->
    <link rel="stylesheet" href="~/Scripts/Material/material-extension-dropdownlist.css" />
    <script defer src="~/Scripts/Material/material-extension-dropdownlist.js"></script>
    <!-- font awesome -->
    <link rel="stylesheet" href="~/Scripts/Material/font-awesome-4.6.3/css/font-awesome.min.css" />
    <!-- validação -->
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
    <!-- customizado -->
    <link rel="stylesheet" href="~/Scripts/Material/material-custom.css" />
    <link rel="stylesheet" href="~/Scripts/Material/custom.css" />
    <script src="~/Scripts/Material/custom.js"></script>
    <script src="~/Scripts/Material/MaterialDialogBuilder.js"></script>
    <script src="~/Scripts/Material/GenericAjax.js"></script>
    <script src="~/Scripts/Material/Notifications.js"></script>

    @{
        //var erroMsg = TempData["ErroMsg"];
        //var sucessoMsg = TempData["SucessoMsg"];
        String infoMsg = ViewBag.InfoMsg ?? null;
    }

    <title>FMB Transparência</title>
</head>

<body style="display:none">

    @*CAIXAS DE DIÁLOGO*@
    <dialog class="mdl-dialog" id="default-dialog">
        <h5 class="mdl-dialog__title"></h5>
        <div class="mdl-dialog__content">
            <p>
            </p>
        </div>
        <div class="mdl-dialog__actions">
        </div>
    </dialog>

    @*Codificar caixas de diálogo com aspecto de notificação, recuadas à direita.
    Usar calc(% + px) para o recuo.*@
    <div class="notification-box">
        <div class="mdl-grid">
            <div class="mdl-cell mdl-cell--11-col-desktop mdl-cell--7-col-tablet mdl-cell--3-col-phone">
                <i class="fa fa-info-circle fa-3x"></i>
            </div>
            <div class="mdl-cell mdl-cell--1-col" style="text-align:right">
                <a onclick="$('.notification-box').hide('fade', 600)" class="close-icon">
                    <i class="fa fa-close"></i>
                </a>
            </div>
            <div class="mdl-cell mdl-cell--10-col box-content">
            </div>
        </div>
    </div>

    @if (!String.IsNullOrEmpty(ViewBag.InfoMsg))
    {
        <script type="text/javascript">
            showNotification("@ViewBag.InfoMsg");
        </script>
    }

    @*CABEÇALHO*@
    <div class="mdl-layout mdl-js-layout mdl-layout--fixed-header">

        <header class="mdl-layout__header ">
            <div class="mdl-layout__header-row">
                <span class="mdl-layout-title">
                    <img src="~/Content/img/fmb.png" class="logo-header" />
                </span>
                <div class="mdl-layout-spacer"></div>
                <nav class="mdl-navigation">
                    <a class="mdl-navigation__link" href="">
                        <i class="fa fa-user"></i>
                        Autenticar
                    </a>

                    <a class="mdl-navigation__link mdl-cell--hide-tablet mdl-cell--hide-phone" href="">
                        <i class="fa fa-question-circle-o"></i>
                        Ajuda
                    </a>
                </nav>
            </div>
        </header>

        @*MENU LATERAL*@
        <div class="mdl-layout__drawer">
            @*<span class="mdl-layout-title">
                    <img src="~/Content/img/fmb.png" class="logo-header" />
                </span>*@

            <nav class="mdl-navigation">
                <a href='@Url.Action("Index")' class="menu-link mdl-navigation__link"><i class="fa fa-search"></i> Consulta</a>
                <a href='@Url.Action("Cadastro")' class="menu-link mdl-navigation__link"><i class="fa fa-plus-square-o"></i> Cadastro</a>
            </nav>
        </div>

        @*CONTEUDO PRINCIPAL*@
        <main class="mdl-layout__content">

            @RenderBody()

        </main>

        @*RODAPÉ*@
        <footer class="mdl-mini-footer">
            <div class="mdl-mini-footer__left-section">
                <ul class="mdl-mini-footer__link-list">
                    <li>&copy; Todos os direitos reservados</li>
                </ul>
            </div>
        </footer>
    </div>


    @RenderSection("AfterStyle", required: false)


    <!-- SCRIPT DA CAIXA DE DIÁLOGO -->
    <script type="text/javascript">
        var dialog = document.querySelector('dialog');

        if (!dialog.showModal) {
            dialogPolyfill.registerDialog(dialog);
        }
    </script>


    @RenderSection("AfterScript", required: false)


    @*ANIMAÇÃO DE ABERTURA DAS TELAS QUE USEM ESTA MASTER PAGE*@
    <script type="text/javascript">
        $("body").show("fade", 600);
    </script>

</body>
</html>

FMB Transp CRUD/WebApp/Views/MasterPages/_Paginador.cshtml
@using PagedList;
@using PagedList.Mvc;
@model IPagedList
<div class="row">
    @if (Model.TotalItemCount > 0)
    {
        <div class="col-sm-6">
            <div class="dataTables_paginate" style="text-align: left;">
                @Html.PagedListPager(Model, null, new PagedListRenderOptions()
                {
                    DisplayLinkToFirstPage = PagedListDisplayMode.Never,
                    DisplayLinkToLastPage = PagedListDisplayMode.Never,
                    DisplayLinkToPreviousPage = PagedListDisplayMode.Never,
                    DisplayLinkToNextPage = PagedListDisplayMode.Never,
                    DisplayLinkToIndividualPages = false,
                    DisplayPageCountAndCurrentLocation = false,
                    DisplayEllipsesWhenNotShowingAllPageNumbers = true,
                    ItemSliceAndTotalFormat = "Exibindo itens de {0} a {1} em um total {2}.",
                    DisplayItemSliceAndTotal = true
                })
            </div>
        </div>
        <div class="col-sm-6">
            <div class="dataTables_paginate" style="text-align: right;">
                @Html.PagedListPager(Model, page => Url.Action("obterPagina", new {pagina = page}),
                    PagedListRenderOptions.EnableUnobtrusiveAjaxReplacing(new AjaxOptions() {HttpMethod = "POST", UpdateTargetId = "linhas", OnComplete = "PagedOnComplete"}))
            </div>
        </div>
    }
    else
    {
        <div class="col col-sm-3"></div>
        <div class="col col-sm-6 widget-body">
            <div class="alert adjusted alert-info alert-block fade in">
                <button class="close" data-dismiss="alert">
                    ×
                </button>
                <i class="fa-fw fa fa-info fa-2x"></i>
                <strong>Info!</strong> Nenhum registro encontrado.
            </div>
        </div>
        <div class="col col-sm-3"></div>
    }
</div>

FMB Transp CRUD/WebApp/Views/PlanoDeContas/Cadastro.cshtml
@using Amon.Modelo.Entidades
@using Amon.Web.Utils;

@model PlanoDeContas

@{
    Layout = "~/Views/MasterPages/_LayoutPadrao.cshtml";
}

<div class="mdl-grid">

    <div class="mdl-cell mdl-cell--12-col mdl-cell--8-col-tablet mdl-cell--4-col-phone">

        <!-- CARD FORM FILTRO -->
        <div class="mdl-card mdl-shadow--2dp">

            @using (Html.BeginForm("Cadastrar", "PlanoDeContas", FormMethod.Post, new { Id = "form-principal" }))
            {
                //@Html.ValidationSummary()

                <div class="mdl-grid">

                    <div class="mdl-cell--12-col form-title">
                        Cadastro Planos de Contas
                    </div>


                    <div class="mdl-cell--4-col">
                        <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
                            @Html.TextBoxFor(Model => Model.CodCli, new { @class = "mdl-textfield__input", Value = "", pattern = REGEX.numerico })
                            @Html.Label("Código cliente", new { @class = "mdl-textfield__label" })
                        </div>
                    </div>


                    <div class="mdl-cell--4-col">
                        <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
                            @Html.TextBoxFor(Model => Model.CodContas, new { @class = "mdl-textfield__input", Value = "", pattern = REGEX.numerico })
                            @Html.Label("Código conta", new { @class = "mdl-textfield__label" })
                        </div>
                    </div>


                    <div class="mdl-cell--4-col">
                        <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
                            @Html.TextBoxFor(Model => Model.ContaReduz, new { @class = "mdl-textfield__input", Value = "", maxlength = "10", pattern = REGEX.numerico })
                            @Html.Label("Código da conta reduzido", new { @class = "mdl-textfield__label" })
                        </div>
                    </div>


                    <div class="mdl-cell--4-col">
                        <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
                            @Html.TextBoxFor(Model => Model.Descricao, new { @class = "mdl-textfield__input", Value = "", maxlength = "80", pattern = REGEX.textoLivre })
                            @Html.Label("Descrição", new { @class = "mdl-textfield__label" })
                        </div>
                    </div>
                    

                    <div class="mdl-cell--4-col">
                        <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
                            @Html.TextBoxFor(Model => Model.ValorOriginal, new { @class = "mdl-textfield__input input-money", Value = "", pattern = REGEX.monetario })
                            @Html.Label("Valor original", new { @class = "mdl-textfield__label" })
                        </div>
                    </div>


                    <div class="mdl-cell--4-col">
                        <label for="cb1" class="mdl-checkbox mdl-js-checkbox mdl-js-ripple-effect">
                            @Html.CheckBoxFor(Model => Model.Analitica, new { @class = "mdl-checkbox__input", Id = "cb1" })
                            <span class="mdl-checkbox__label">Analítica</span>
                        </label>
                    </div>




                    <div class="mdl-cell--12-col">
                        <div class="mdl-card__actions">
                            <button type="reset" class="mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect mdl-button--primary secondary-action acao-secundaria">Limpar</button>
                            
                            <button type="submit" class="mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect mdl-button--accent primary-action" formnovalidate>Cadastrar</button>
                        </div>
                    </div>

                </div>
            }
        </div>
    </div>
</div>



<!--  SESSÃO DE SCRIPT (NÃO OBRIGATÓRIA) A SER EXECUTADA APÓS O CARREGAMENTO DESTA VIEW -->
@section AfterScript {
    <script type="text/javascript">
        $(function () {
            //$(".input-money").focusin(function () {
            //    var valor = $(this).val();
            //    if (valor === "") {
            //        $(this).val("R$ " + valor);
            //    }
            //});
            //$(".input-money").focusout(function () {
            //    if ($(this).val() === "R$ ") {
            //        $(this).val("");
            //    }
            //});

            //Trata a submissão do Form
            $("#form-principal").submit(function (e) {
                $("#form-principal input, #form-principal select").each(function () {
                    if ($(this).val() === "") {
                        showNotification("Todos os campos são obrigatórios!");
                        e.preventDefault();
                        return false;
                    }
                });
            });
        });
    </script>
}

<script type="text/javascript" src="~/Scripts/DynamicActions/PlanoContasListagemEvents.js"></script>

@section AfterStyle {
    <style type="text/css">
    </style>
}